const PHONETICS = {
  "abandon": "/ʌbˈændʌn/",
  "aboard": "/ʌbˈɔrd/",
  "absorb": "/ʌbzˈɔrb/",
  "abuse": "/ʌbjˈus/",
  "adversity": "/ædvˈɝsɪtˌi/",
  "advertise": "/ˈædvɝtˌaɪz/",
  "advertising": "/ˈædvɝtˌaɪzɪŋ/",
  "agenda": "/ʌdʒˈɛndʌ/",
  "alcohol": "/ˈælkʌhˌɑl/",
  "amateur": "/ˈæmʌtˌɝ/",
  "animation": "/ˌænʌˈmeɪʃʌn/",
  "annual": "/ˈænjuʌl/",
  "antarctica": "/ˌænˈtɑrktɪkʌ/",
  "arch": "/ˈɑrtʃ/",
  "arched": "/ˈɑrtʃt/",
  "aristotle": "/ˈɛrʌstˌɑtʌl/",
  "artistic": "/ɑrtˈɪstɪk/",
  "assign": "/ʌsˈaɪn/",
  "await": "/ʌwˈeɪt/",
  "banjo": "/bˈændʒˌoʊ/",
  "bark": "/bˈɑrk/",
  "barren": "/bˈærʌn/",
  "basin": "/bˈeɪsʌn/",
  "bat": "/bˈæt/",
  "be composed of": "/bˈi kʌmpˈoʊzd ˈʌv/",
  "be fond of": "/bˈi fˈɑnd ˈʌv/",
  "be made up of": "/bˈi mˈeɪd ˈʌp ˈʌv/",
  "be worthy of": "/bˈi wˈɝði ˈʌv/",
  "beard": "/bˈɪrd/",
  "bee": "/bˈi/",
  "belongings": "/bɪlˈɔŋɪŋz/",
  "billy goat": "/bˈɪli ɡˈoʊt/",
  "bitter": "/bˈɪtɝ/",
  "blank": "/blˈæŋk/",
  "blanket": "/blˈæŋkʌt/",
  "blossom": "/blˈɑsʌm/",
  "bowling": "/bˈoʊlɪŋ/",
  "brass": "/brˈæs/",
  "breakthrough": "/brˈeɪkθrˌu/",
  "bride": "/brˈaɪd/",
  "bring … to life": "/brˈɪŋ tˈu lˈaɪf/",
  "broadcast": "/brˈɔdkˌæst/",
  "bronze": "/brˈɑnz/",
  "buddhism": "/bˈudɪzʌm/",
  "buddhist": "/bˈudʌst/",
  "bull": "/bˈʊl/",
  "butterfly": "/bˈʌtɝflˌaɪ/",
  "campaign": "/kæmpˈeɪn/",
  "candidate": "/kˈændʌdeɪt/",
  "carbon": "/kˈɑrbʌn/",
  "carbon dioxide": "/kˈɑrbʌn daɪˈɑksˌaɪd/",
  "ceramic": "/sɝˈæmɪk/",
  "chaos": "/kˈeɪɑs/",
  "cherry": "/tʃˈɛri/",
  "cherry blossom": "/tʃˈɛri blˈɑsʌm/",
  "christianity": "/krˌɪstʃˈiænɪti/",
  "cigarette": "/sˌɪɡˈɝɛt/",
  "civil": "/sˈɪvʌl/",
  "civilian": "/sʌvˈɪljʌn/",
  "claude monet": "/klˈɔd moʊnˈeɪ/",
  "clearing after snow on a mountain pass": "/klˈɪrɪŋ ˈæftɝ snˈoʊ ˈɑn ʌ mˈaʊntʌn pˈæs/",
  "client": "/klˈaɪʌnt/",
  "clover": "/klˈoʊvɝ/",
  "comedy": "/kˈɑmʌdi/",
  "commitment": "/kʌmˈɪtmʌnt/",
  "complicated": "/kˈɑmplʌkˌeɪtʌd/",
  "compose": "/kʌmpˈoʊz/",
  "comprehension": "/kˌɑmpriˈhɛnʃʌn/",
  "comprehensive": "/kˌɑmpriˈhɛnsɪv/",
  "confucianism": "/kʌnfjˈuʃʌnˌɪzʌm/",
  "conservation": "/kˌɑnsɝˈveɪʃʌn/",
  "consultant": "/kʌnsˈʌltʌnt/",
  "contemporary": "/kʌntˈɛmpɝˌɛri/",
  "contest": "/kˈɑntɛst/",
  "convey": "/kʌnvˈeɪ/",
  "core": "/kˈɔr/",
  "corporate": "/kˈɔrpɝʌt/",
  "correspond": "/kˌɔrʌsˈpɑnd/",
  "correspondence": "/kˌɔrʌsˈpɑndʌns/",
  "cosy (name cozy)": "/kˈoʊzi/",
  "crew": "/krˈu/",
  "criticism": "/krˈɪtɪsˌɪzʌm/",
  "cruel": "/krˈuʌl/",
  "crush": "/krˈʌʃ/",
  "cubism": "/kjˈubɪzʌm/",
  "cue": "/kjˈu/",
  "cupboard": "/kˈʌbɝd/",
  "damp": "/dˈæmp/",
  "dawn": "/dˈɔn/",
  "deadline": "/dˈɛdlˌaɪn/",
  "decent": "/dˈisʌnt/",
  "decide on": "/dˌɪˈsaɪd ˈɑn/",
  "decline": "/dɪklˈaɪn/",
  "delete": "/dɪlˈit/",
  "delicate": "/dˈɛlʌkʌt/",
  "dentist": "/dˈɛntʌst/",
  "diamond": "/dˈaɪmʌnd/",
  "dimension": "/dɪmˈɛnʃʌn/",
  "dioxide": "/daɪˈɑksˌaɪd/",
  "discipline": "/dˈɪsʌplʌn/",
  "disposal": "/dɪspˈoʊzʌl/",
  "disturb": "/dɪstˈɝb/",
  "dizzy": "/dˈɪzi/",
  "dominant": "/dˈɑmʌnʌnt/",
  "dominate": "/dˈɑmʌnˌeɪt/",
  "dozen": "/dˈʌzʌn/",
  "dozens of": "/dˈʌzʌnz ˈʌv/",
  "drama": "/drˈɑmʌ/",
  "drug": "/drˈʌɡ/",
  "dynamic": "/daɪnˈæmɪk/",
  "ecology": "/ɪkˈɑlʌdʒi/",
  "elizabeth barrett browning": "/ɪlˈɪzʌbʌθ bˈærɪt brˈaʊnɪŋ/",
  "emerge": "/ɪmˈɝdʒ/",
  "emission": "/ɪmˈɪʃʌn/",
  "endurance": "/ˈɛndɝʌns/",
  "enhance": "/ɛnhˈæns/",
  "enterprise": "/ˈɛntɝprˌaɪz/",
  "enthusiastic": "/ɪnθˌuzˈiæstɪk/",
  "entry": "/ˈɛntri/",
  "envy": "/ˈɛnvi/",
  "episode": "/ˈɛpʌsˌoʊd/",
  "era": "/ˈɛrʌ/",
  "ernest shackleton": "/ˈɝnʌst ʃˈækʌltʌn/",
  "escalator": "/ˈɛskʌlˌeɪtɝ/",
  "examine": "/ɪɡzˈæmɪn/",
  "exhibition": "/ˌɛksʌˈbɪʃʌn/",
  "expansion": "/ɪkspˈænʃʌn/",
  "expedition": "/ˌɛkspʌˈdɪʃʌn/",
  "facilitate": "/fʌsˈɪlʌtˌeɪt/",
  "feeling from mountain and water": "/fˈilɪŋ frˈʌm mˈaʊntʌn ʌnd wˈɔtɝ/",
  "fine": "/fˈaɪn/",
  "fine art (also fine arts)": "/fˈaɪn ˈɑrt/",
  "flu": "/flˈu/",
  "folk": "/fˈoʊk/",
  "fond": "/fˈɑnd/",
  "footprint": "/fˈʊtprˌɪnt/",
  "format": "/fˈɔrmˌæt/",
  "fortunately": "/fˈɔrtʃʌnʌtli/",
  "fossil": "/fˈɑsʌl/",
  "fossil fuel": "/fˈɑsʌl fjˈuʌl/",
  "frame": "/frˈeɪm/",
  "frank wild": "/frˈæŋk wˈaɪld/",
  "frank worsley": "/frˈæŋk wˈɝsli/",
  "frequently": "/frˈikwʌntli/",
  "fuel": "/fjˈuʌl/",
  "furniture": "/fˈɝnɪtʃɝ/",
  "garbage": "/ɡˈɑrbɪdʒ/",
  "genuine": "/dʒˈɛnjʌwʌn/",
  "give off": "/ɡˈɪv ˈɔf/",
  "good/bad-tempered": "/ɡˈʊd bˈæd-tˈɛmpɝd/",
  "graph": "/ɡrˈæf/",
  "grief": "/ɡrˈif/",
  "guarantee": "/ɡˌɛrʌnˈti/",
  "guidance": "/ɡˈaɪdʌns/",
  "habitable": "/hˈæbʌtʌbʌl/",
  "haiku": "/hˈaɪku/",
  "harmonious": "/hɑrmˈoʊniʌs/",
  "hubert hudson": "/hjˈubɝt hˈʌdsʌn/",
  "humanistic": "/hjˌumʌˈnɪstɪk/",
  "humanity": "/hjumˈænɪti/",
  "humble": "/hˈʌmbʌl/",
  "hurricane katrina": "/hˈɝʌkˌeɪn kʌtrˈinʌ/",
  "imagery": "/ˈɪmʌdʒri/",
  "implement": "/ˈɪmplʌmʌnt/",
  "impressionism": "/ˌɪmpˈrɛʃʌnˌɪzʌm/",
  "in particular": "/ɪn pɝtˈɪkjʌlɝ/",
  "in response to": "/ɪn rɪspˈɑns tˈu/",
  "influential": "/ˌɪnflˈuɛnʃʌl/",
  "ink": "/ˈɪŋk/",
  "innocence": "/ˈɪnʌsʌns/",
  "innocent": "/ˈɪnʌsʌnt/",
  "inspection": "/ˌɪnsˈpɛkʃʌn/",
  "investment": "/ˌɪnˈvɛstmʌnt/",
  "jungle": "/dʒˈʌŋɡʌl/",
  "langston hughes": "/lˈæŋstʌn hjˈuz/",
  "lawn": "/lˈɔn/",
  "leonardo da vinci": "/lˌiʌˈnɑrdoʊ dˈɑ vˈɪnsi/",
  "liberation": "/lˌɪbˈˌɝeɪʃʌn/",
  "lionel greenstreet": "/lˈaɪʌnʌl ɡrˈinstrˌit/",
  "literary": "/lˈɪtɝˌɛri/",
  "loyal": "/lˈɔɪʌl/",
  "make fire": "/mˈeɪk fˈaɪɝ/",
  "make up one’s mind": "/mˈeɪk ˈʌp mˈaɪnd/",
  "melt": "/mˈɛlt/",
  "memorial": "/mʌmˈɔriʌl/",
  "methane": "/mˈɛθˌeɪn/",
  "michelangelo": "/mˌaɪkʌˈlændʒʌlˌoʊ/",
  "miserable": "/mˈɪzɝʌbʌl/",
  "mockingbird": "/mˈɑkɪŋbˌɝd/",
  "moderate": "/mˈɑdɝʌt/",
  "monthly": "/mˈʌnθli/",
  "mood": "/mˈud/",
  "motive": "/mˈoʊtɪv/",
  "motor": "/mˈoʊtɝ/",
  "mythology": "/mʌθˈɑlʌdʒˌi/",
  "navigator": "/nˈævʌɡˌeɪtɝ/",
  "navy": "/nˈeɪvi/",
  "negative": "/nˈɛɡʌtɪv/",
  "nephew": "/nˈɛfju/",
  "noble": "/nˈoʊbʌl/",
  "norway": "/nˈɔrwˌeɪ/",
  "nuclear": "/nˈukliɝ/",
  "nursery": "/nˈɝsɝi/",
  "nursery rhyme": "/nˈɝsɝi rˈaɪm/",
  "nut": "/nˈʌt/",
  "on behalf of": "/ˈɑn bɪhˈæf ˈʌv/",
  "originate": "/ɝˈɪdʒʌnˌeɪt/",
  "outer": "/ˈaʊtɝ/",
  "penguin": "/pˈɛŋɡwʌn/",
  "people’s liberation army (pla)": "/pˈipʌl ˈɛs lˌɪbˈˌɝeɪʃʌn ˈɑrmi/",
  "permanent": "/pˈɝmʌnʌnt/",
  "perseverance": "/pˌɝsʌˈvɪrʌns/",
  "persevere": "/pɝsʌvˈɪr/",
  "pessimistic": "/pˌɛsʌˈmɪstɪk/",
  "photography": "/fʌtˈɑɡrʌfi/",
  "physical": "/fˈɪzɪkʌl/",
  "picasso": "/pɪkˈɑsoʊ/",
  "pill": "/pˈɪl/",
  "policy": "/pˈɑlʌsi/",
  "polish": "/pˈɑlɪʃ/",
  "pond": "/pˈɑnd/",
  "precise": "/prɪsˈaɪs/",
  "precisely": "/prɪsˈaɪsli/",
  "prejudice": "/prˈɛdʒʌdɪs/",
  "primitive": "/prˈɪmʌtɪv/",
  "prose": "/prˈoʊz/",
  "psychology": "/saɪkˈɑlʌdʒi/",
  "purchase": "/pˈɝtʃʌs/",
  "qualified": "/kwˈɑlʌfˌaɪd/",
  "racial": "/rˈeɪʃʌl/",
  "rank": "/rˈæŋk/",
  "raphael": "/rˌɑfˈaɪɛl/",
  "realism": "/rˈiʌlɪzʌm/",
  "realist": "/rˈiʌlɪst/",
  "realistic": "/rˌiʌˈlɪstɪk/",
  "recite": "/rʌsˈaɪt/",
  "recognition": "/rˌɛkʌɡˈnɪʃʌn/",
  "recreation": "/rˌɛkrˈieɪʃʌn/",
  "reform": "/rʌfˈɔrm/",
  "refresh": "/rɪfrˈɛʃ/",
  "regulation": "/rˌɛɡjʌˈleɪʃʌn/",
  "release": "/rilˈis/",
  "rely": "/rɪlˈaɪ/",
  "rely on": "/rɪlˈaɪ ˈɑn/",
  "rembrandt": "/rˈɛmbrˌænt/",
  "renoir": "/rɛnwˈɑr/",
  "repeatedly": "/rɪpˈitɪdli/",
  "representative": "/rˌɛprʌˈzɛntʌtɪv/",
  "reputation": "/rˌɛpjʌˈteɪʃʌn/",
  "resolution": "/rˌɛzʌˈluʃʌn/",
  "resolve": "/rizˈɑlv/",
  "respective": "/rɪspˈɛktɪv/",
  "respectively": "/rɪspˈɛktɪvli/",
  "restore": "/rɪstˈɔr/",
  "restrict": "/ristrˈɪkt/",
  "restriction": "/ristrˈɪkʃʌn/",
  "revolve": "/rivˈɑlv/",
  "reward": "/rɪwˈɔrd/",
  "rhyme": "/rˈaɪm/",
  "rhythm": "/rˈɪðʌm/",
  "robert browning": "/rˈɑbɝt brˈaʊnɪŋ/",
  "rough": "/rˈʌf/",
  "rugby": "/rˈʌɡbi/",
  "sculptor": "/skˈʌlptɝ/",
  "sculpture": "/skˈʌlptʃɝ/",
  "seal": "/sˈil/",
  "seed": "/sˈid/",
  "seize": "/sˈiz/",
  "selfish": "/sˈɛlfɪʃ/",
  "sensitive": "/sˈɛnsʌtɪv/",
  "set apart from": "/sˈɛt ʌpˈɑrt frˈʌm/",
  "shakespeare": "/ʃˈeɪkspˌir/",
  "shave": "/ʃˈeɪv/",
  "shave off": "/ʃˈeɪv ˈɔf/",
  "shelf": "/ʃˈɛlf/",
  "sink": "/sˈɪŋk/",
  "skateboard": "/skˈeɪtbˌɔrd/",
  "skip": "/skˈɪp/",
  "smog": "/smˈɑɡ/",
  "sonnet": "/sˈɑnɪt/",
  "sonnets from the portuguese": "/sˈɑnɪts frˈʌm ðʌ pˈɔrtʃʌɡˌiz/",
  "sorrow": "/sˈɑroʊ/",
  "south georgia island": "/sˈaʊθ dʒˈɔrdʒʌ ˈaɪlʌnd/",
  "sow": "/sˈaʊ/",
  "specialist": "/spˈɛʃʌlʌst/",
  "starve": "/stˈɑrv/",
  "steward": "/stˈuɝd/",
  "stimulate": "/stˈɪmjʌlˌeɪt/",
  "stove": "/stˈoʊv/",
  "straight away": "/strˈeɪt ʌwˈeɪ/",
  "stressed out": "/strˈɛst ˈaʊt/",
  "string": "/strˈɪŋ/",
  "subjective": "/sʌbdʒˈɛktɪv/",
  "submit": "/sʌbmˈɪt/",
  "subsequent": "/sˈʌbsʌkwʌnt/",
  "sugary": "/ʃˈʊɡɝi/",
  "sunrise": "/sˈʌnrˌaɪz/",
  "surgeon": "/sˈɝdʒʌn/",
  "surgery": "/sˈɝdʒɝi/",
  "sustain": "/sʌstˈeɪn/",
  "sustainable": "/sʌstˈeɪnʌbʌl/",
  "syllable": "/sˈɪlʌbʌl/",
  "sympathetic": "/sˌɪmpʌˈθɛtɪk/",
  "sympathy": "/sˈɪmpʌθi/",
  "symphony": "/sˈɪmfʌni/",
  "tadpoles searching for mother": "/tˈædpˌoʊlz sˈɝtʃɪŋ fˈɔr mˈʌðɝ/",
  "tease": "/tˈiz/",
  "the antarctic": "/ðʌ æntˈɑrktɪk/",
  "the cowboy’s flute": "/ðʌ kˈaʊbˌɔɪ ˈɛs flˈut/",
  "the crescent moon": "/ðʌ krˈɛsʌnt mˈun/",
  "the middle ages": "/ðʌ mˈɪdʌl ˈeɪdʒʌz/",
  "the renaissance": "/ðʌ rˌɛnʌˈsɑns/",
  "the south pole": "/ðʌ sˈaʊθ pˈoʊl/",
  "the victorian era": "/ðʌ vɪktˈɔriʌn ˈɛrʌ/",
  "thorough": "/θˈɝoʊ/",
  "tobacco": "/tʌbˈækˌoʊ/",
  "tolerate": "/tˈɑlɝˌeɪt/",
  "tom crean": "/tˈɑm krˈin/",
  "trend": "/trˈɛnd/",
  "tropical": "/trˈɑpɪkʌl/",
  "two-dimensional": "/tˈu-dɪmˈɛnʃʌnʌl/",
  "undergo": "/ˌʌndɝˈɡoʊ/",
  "unfortunately": "/ʌnfˈɔrtʃʌnʌtli/",
  "utter": "/ˈʌtɝ/",
  "variation": "/vˌɛrˈieɪʃʌn/",
  "vase": "/vˈeɪs/",
  "verse": "/vˈɝs/",
  "version": "/vˈɝʒʌn/",
  "visual": "/vˈɪʒʌwʌl/",
  "volume": "/vˈɑljum/",
  "voyage": "/vˈɔɪʌdʒ/",
  "wage": "/wˈeɪdʒ/",
  "water lily": "/wˈɔtɝ lˈɪli/",
  "waterway": "/wˈɔtɝwˌeɪ/",
  "wherever": "/wɛrˈɛvɝ/",
  "worldwide": "/wˈɝldwaɪd/",
  "worn out": "/wˈɔrn ˈaʊt/",
  "worthy": "/wˈɝði/"
};

